### ISSUE TITLE
[线下活动]关于《开源人线下见面会》活动的反馈

### ISSUE THREAD

**Issue by kylezhang** [jenkins-zh/jenkins-zh#107]
> 非常感谢https://jenkins-zh.cn 帮助中国的个人与企业很好的落地Jenkins，本Issue主要对2019年8月24日线下活动《开源人线下见面会》的反馈。

主要从一个活动的角度提出；

No. | 反馈点 | 问题 | 参考意见
--- | --- | --- | ---
1 | Speaker演讲时间 | 超时 | 有时间提醒
2 | panel环节 | 每个讨论者应该精简观点 | 主持人可以引导，</br> eg：</br> 大家把这个问题的看法总结1，2，3点；</br> 及时合理的切断专家发言 etc.
3 | panel环节 | 互动少 | 作为一个free、open为核心的活动，应该也把本次参与者的意见考虑进来
4 | Jenkins-zh logo | Jenkins-zh logo、形象展示太少 | 可以比较精心的设计logo、形象等，可以贴在某地、可以在speaker演讲完或者panel阶段的背景为Jenkins-zh logo或者形象

**Comment by yJunS** [comment]
感谢反馈，我们确实还有很多不足的地方，多谢指正

**Comment by LinuxSuRen** [comment]
> 有时间提醒

这个是有提醒的，但还是得让讲师来结束分享。不过，我们后续可以提前告知讲师时长的问题。

其他的建议也都非常的有学习的意义。
