### ISSUE TITLE
调研 discourse，准备作为社区的官方论坛

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-zh/jenkins-zh#121]
discourse 项目链接 https://github.com/discourse/discourse

**Comment by yJunS** [comment]
> 初次尝试安装失败

-  安装环境：
  * Centos 7.x
  * Docker
  * Ruby、PostgreSQL、Redis
  * git

- 安装结果
失败

- 可能原因
 * 推荐为 ubuntu 环境安装。暂无 ubuntu 环境
 * 也可能有 Ruby、PostgreSQL、Redis 等软件版本因素的原因

**Comment by LinuxSuRen** [comment]
有更具体的错误信息吗？

**Comment by yJunS** [comment]
![image](https://user-images.githubusercontent.com/20575981/65581575-4d8e8480-dfae-11e9-83cd-6c440c4b00eb.png)
![image](https://user-images.githubusercontent.com/20575981/65581553-3fd8ff00-dfae-11e9-84de-0d82629259df.png)

**Comment by LinuxSuRen** [comment]
另外一个类似的，用 go 写的项目是 https://github.com/satellity/satellity，看起来比较简单。

**Comment by donhui** [comment]
个人觉得还是 discourse 比较好，它的功能比较强大，有很多社区在用...
我也是看了这个 issue ，才知道这个产品是 discourse

**Comment by LinuxSuRen** [comment]
discourse 是比较好的一个项目，不过看起来部署比较复杂。要是能容易变成容器部署的话，就很好了。

**Comment by yJunS** [comment]
不行的话。我把我那台虚机装成ubutnu。然后试试

**Comment by LinuxSuRen** [comment]
不仅仅是现在调研的问题，最终使用的话，也希望是能简单，并跑在容器里。

**Comment by yJunS** [comment]
最终是跑在容器中，只不过可能是项目本身的限制，需要按照他的方式去运行。自动运行在容器里

**Comment by yJunS** [comment]
基于ubuntu部署成功了
![image](https://user-images.githubusercontent.com/20575981/65738408-4d0ffe00-e114-11e9-951a-0f26a1450dd1.png)

**Comment by yJunS** [comment]
目前管理员邮箱注册，邮件发送不成功。未找到原因

**Comment by LinuxSuRen** [comment]
看看这里的描述是否有帮助 https://meta.discourse.org/t/troubleshooting-email-on-a-new-discourse-install/16326/114

**Comment by yJunS** [comment]
这个开始就看过了。没有太大的用处

**Comment by LinuxSuRen** [comment]
那现在还有其他的思路吗？

**Comment by yJunS** [comment]
看到应该网上有人安装过。  看看有没有遇到相同问题的

**Comment by LinuxSuRen** [comment]
应该有很多人都安装过了，可能是遇到的问题有细微的不同。我感觉关键在于如何能拿到对应的日志输出。

**Comment by donhui** [comment]
或者换个发件邮箱试试？

**Comment by yJunS** [comment]
我看着好像写着在阿里上装有要改的地方。   我改了  看看效果

**Comment by LinuxSuRen** [comment]
还是的知道如何查看日志，不然后续我们遇到问题也不好排查。

**Comment by yJunS** [comment]
![image](https://user-images.githubusercontent.com/20575981/65824854-17991b00-e2a2-11e9-855e-9d0345b8fb70.png)
从他给排查的方式里的日志文件。信息太少

**Comment by LinuxSuRen** [comment]
是否发到了垃圾邮箱里了呢？

**Comment by yJunS** [comment]
https://meta.discoursecn.org/t/topic/28
https://meta.discoursecn.org/t/topic/26
https://meta.discoursecn.org/t/%E5%9B%BD%E5%86%85%E9%82%AE%E7%AE%B1%E6%97%A0%E6%B3%95%E5%8F%91%E9%80%81%E9%82%AE%E4%BB%B6/592
https://meta.discoursecn.org/t/%E5%9C%A8%E9%98%BF%E9%87%8C%E4%BA%91%E4%B8%8A%E5%AE%89%E8%A3%85-Docker/27
https://meta.discoursecn.org/t/topic/2816/1
https://meta.discoursecn.org/t/topic/2738

**Comment by yJunS** [comment]
换了mailgun出现
![image](https://user-images.githubusercontent.com/20575981/65830051-a6c42400-e2de-11e9-8250-2b5749d1ab9c.png)

**Comment by yJunS** [comment]
开始就注意了垃圾邮箱了，一直都没有

**Comment by yJunS** [comment]
![image](https://user-images.githubusercontent.com/20575981/65848829-6ade9c80-e37a-11e9-8494-2c8ea7661e3a.png)
使用mailgun应该是调用成功了。不过不知道是在哪需要配置

**Comment by LinuxSuRen** [comment]
没有明白是什么意思

**Comment by yJunS** [comment]
![image](https://user-images.githubusercontent.com/20575981/65866778-fe7a9200-e3a7-11e9-85b8-a9bbcbfb27b6.png)
@LinuxSuRen 这些你需要设置一下

**Comment by yJunS** [comment]
已经测试部署成功
![image](https://user-images.githubusercontent.com/20575981/65880177-fe888b00-e3c3-11e9-8d43-f69c3891e4e5.png)

**Comment by LinuxSuRen** [comment]
已经完成 https://community.jenkins-zh.cn/
