### ISSUE TITLE
建设国内的 Jenkins update center

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-zh/jenkins-zh#148]
由于 Jenkins 会检查来自于 update center 的 json 文件的签名，因此，我们除了需要利用下面的脚本把镜像地址的缓存文件修改以外，还需要对此生成证书。

```
cat  update-center.json | sed -e 's/http:\/\/updates.jenkins-ci.org\/download\//https:\/\/mirrors.tuna.tsinghua.edu.cn\/jenkins\//g' > new.json
```

最后，我们会把搭建好的更新中心作为 https://jenkins-zh.cn/ 的子域名上线。

另外，国内有多个镜像中心，我们可以借此很方便地对[多个中心](https://jenkins-zh.cn/tutorial/management/mirror/)进行支持。

本方案是由清华大学开源镜像站 tuna/issues#659 引出来的。

**Comment by donhui** [comment]
update-center.json 文件中
"connectionCheckUrl":"http://www.google.com/"
google 可以换成 baidu

**Comment by LinuxSuRen** [comment]
嗯，可以考虑这个。不过，我目前还不清楚这个配置的具体作用。

**Comment by LinuxSuRen** [comment]
see also jenkins-infra/update-center2#245

**Comment by donhui** [comment]
我理解的这个证书是 https 域名需要的，如果用 http 的话，就不需要证书了
还有如果 jenkins-zh.cn 本身就有证书的话，应该可以用它的证书的吧

**Comment by LinuxSuRen** [comment]
你再仔细看看我贴出来的那个 PR 里的说明，这个证书不是浏览器的，是 Jenkins 要求的。

**Comment by donhui** [comment]
我自己搭建了 nginx ，生成的 update-center.json，不用什么证书也可以用的，下载了 Blue Ocean 插件试了下，速度很快～

**Comment by LinuxSuRen** [comment]
是通过修改 Jenkins 的更新中心地址来做的吗？update-center.json是怎么来的？

**Comment by donhui** [comment]
是通过修改 Jenkins 的更新中心地址来做的，update-center.json 从清华镜像下载的，然后替换了下载地址，刚看了下，虽然功能没问题，但是页面有个警告
![image](https://user-images.githubusercontent.com/5702065/68460857-d5211180-0243-11ea-9e2b-8768b2e9de04.png)

**Comment by LinuxSuRen** [comment]
那如何确定插件就是从清华的站点下载的呢？

**Comment by donhui** [comment]
貌似不确定从哪里下载的，我也挂了代理的 😅
这个目前也没日志，得再看看

**Comment by LinuxSuRen** [comment]
已经搞定了，还差一篇推广的文章。

**Comment by Z0T0** [comment]
你这个国内源，对JDK 有什么要求？

检查更新中心: Signature verification failed in update site &#039;default&#039; <a href='#' class='showDetails'>（显示详情）</a><pre style='display:none'>java.security.cert.CertPathValidatorException: Algorithm constraints check failed on keysize limits. RSA 1024bit key used with certificate: EMAILADDRESS=admin@jenkins-zh.com, CN=demo.com, OU=dev, O=vihoo, L=SZ, ST=GD, C=CN.<br> at sun.security.util.DisabledAlgorithmConstraints$KeySizeConstraint.permits(DisabledAlgorithmConstraints.java:817)

**Comment by LinuxSuRen** [comment]
@Z0T0 感谢提供反馈，我们是在 java8 的环境下做的测试
麻烦给一些您的环境信息：
- Jenkins 版本号
- 运行 Jenkins 的 JRE 版本号
- Jenkins 的安装方式

**Comment by Z0T0** [comment]
首先，非常感谢您的回复:
1. Jenkins版本号:&nbsp;Jenkins ver. 2.190.3
2. Jenkins 的安装方式: war 包
3. 运行Jenkins 的JRE 版本为


您方便告诉我，你们测试的所有环境信息吗？&nbsp; &nbsp;&nbsp;
-----------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhao Xiaojie"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月25日(星期一) 下午2:04
收件人:&nbsp;"jenkins-zh/jenkins-zh"<jenkins-zh@noreply.github.com&gt;;
抄送:&nbsp;"Benson"<1363415101@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [jenkins-zh/jenkins-zh] 建设国内的 Jenkins update center (#148)




@Z0T0 感谢提供反馈，我们是在 java8 的环境下做的测试
 麻烦给一些您的环境信息：
  
Jenkins 版本号
 
运行 Jenkins 的 JRE 版本号
 
Jenkins 的安装方式

**Comment by LinuxSuRen** [comment]
@Z0T0 请问 Java 的版本号是多少呢？

**Comment by Z0T0** [comment]
Java 用的是OpenJDK 11
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhao Xiaojie"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月25日(星期一) 下午2:55
收件人:&nbsp;"jenkins-zh/jenkins-zh"<jenkins-zh@noreply.github.com&gt;;
抄送:&nbsp;"Benson"<1363415101@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [jenkins-zh/jenkins-zh] 建设国内的 Jenkins update center (#148)




@Z0T0 请问 Java 的版本号是多少呢？

**Comment by LinuxSuRen** [comment]
好的，我抽时间做下测试。

**Comment by Z0T0** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhao Xiaojie"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月25日(星期一) 下午2:58
收件人:&nbsp;"jenkins-zh/jenkins-zh"<jenkins-zh@noreply.github.com&gt;;
抄送:&nbsp;"Benson"<1363415101@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [jenkins-zh/jenkins-zh] 建设国内的 Jenkins update center (#148)



好的，我抽时间做下测试。
 
 &gt; On Nov 25, 2019, at 14:57, Z0T0 <notifications@github.com&gt; wrote:
 &gt; 
 &gt; OpenJDK 11 
 &gt; openjdk version "1.8.0_232" 
 &gt; OpenJDK Runtime Environment (build 1.8.0_232-b09) 
 &gt; OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

**Comment by LinuxSuRen** [comment]
> Java 用的是OpenJDK 11
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

@Z0T0 不对吧，到底是用的java11还是8呢？

**Comment by Z0T0** [comment]
我用的是openjdk11, 直接yum 安装的。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhao Xiaojie"<notifications@github.com&gt;; 
发送时间: 2019年11月25日(星期一) 下午3:19
收件人: "jenkins-zh/jenkins-zh"<jenkins-zh@noreply.github.com&gt;; 
抄送: "Benson"<1363415101@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [jenkins-zh/jenkins-zh] 建设国内的 Jenkins update center (#148)



 
Java 用的是OpenJDK 11
 openjdk version "1.8.0_232"
 OpenJDK Runtime Environment (build 1.8.0_232-b09)
 OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
  
@Z0T0 不对吧，到底是用的java11还是8呢？

**Comment by LinuxSuRen** [comment]
@Z0T0 没有明确的复现步骤，是无法复现问题的。

**Comment by yJunS** [comment]
我在 openjdk 11 环境测试是没有问题的, 我的 jdk 版本如下：
```
openjdk version "11.0.1-redhat" 2018-10-16 LTS
OpenJDK Runtime Environment (build 11.0.1-redhat+13-LTS)
OpenJDK 64-Bit Server VM (build 11.0.1-redhat+13-LTS, mixed mode)
```
@Z0T0 个人感觉@Z0T0 没有使用建议用的 update center url，可以发一下你使用的 update center url吗？

**Comment by yJunS** [comment]
今天有一个童鞋也有相同的问题，重新初始化 Jenkins 之后，看到 Jenkins 是离线的，感觉本地网络环境和服务端之间的通信有一定问题。

**Comment by xusiwei** [comment]
> update-center.json 文件中
> `"connectionCheckUrl":"http://www.google.com/"`
> google 可以换成 baidu

这里的 google.com 用来check网络连接，国内很多时候访问不了 http://www.google.com/ 
导致拉取不了更新列表，有点坑。。。。。。

**Comment by LinuxSuRen** [comment]
@xusiwei 可以关注下这个项目 https://github.com/jenkins-zh/update-center-mirror
