### ISSUE TITLE
[推荐] - How We Scaled Jenkins in Less Than a Day

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-zh/jenkins-zh#208]
### 标题
How We Scaled Jenkins in Less Than a Day

### 作者
Gaurav Agarwal

### 来源
medium.com

### 原文链接
https://medium.com/better-programming/how-we-scaled-jenkins-in-less-than-a-day-ccbcada8e4a4

**Comment by walker0921** [comment]
let me have a try
