### ISSUE TITLE
文章中图片无法加载：404

### ISSUE THREAD

**Issue by donhui** [jenkins-zh/jenkins-zh#21]
举个例子：
https://jenkins-zh.cn/wechat/articles/images/articles/2019/03/2019-01-08-mpl-modular-pipeline-library/fig01-layers-of-the-mpl.png
上面url图片无法显示，状态码404，下面的 url 显示是好的：
https://jenkins-zh.cn/images/articles/2019/03/2019-01-08-mpl-modular-pipeline-library/fig01-layers-of-the-mpl.png

**Comment by LinuxSuRen** [comment]
嗯，现在是有这个问题。主要是由于在 GitHub 后构建后的网站路径不一致的问题导致，可以在构建过程中使用脚本动态地把图片路径做替换来修复。

**Comment by donhui** [comment]
> 嗯，现在是有这个问题。主要是由于在 GitHub 后构建后的网站路径不一致的问题导致，可以在构建过程中使用脚本动态地把图片路径做替换来修复。

也可以把images目录mv到wechat/articles/目录下

**Comment by LinuxSuRen** [comment]
嗯，是的这些图片也没有必要在另外一个仓库中保存。

**Comment by donhui** [comment]
先简单修改了下Makefile让图片能显示了
