### ISSUE TITLE
在Jenkins 2.230版本中，中文汉化显示问题

### ISSUE THREAD

**Issue by gesangtome** [jenkins-zh/jenkins-zh#217]
事实上，不仅是Jenkins 2.230， 在以前的版本中也会出现“界面中文语言显示不全”，具体表现在“Jenkins全局设置中，部分选项的语言被翻译，而其他的一些选项依旧是英文“，在Jenkins 2.230中，页面右下角jenkins版本号的前一行，”Jenkins中文社区“显示的位置错位

**Comment by yJunS** [comment]
@gesangtome 你好，可以在 [中文插件](https://github.com/jenkinsci/localization-zh-cn-plugin/issues) 提 issue，最好将截图一起发一下，如果有意愿的话，你也可以提 PR 进行完善。

**Comment by gesangtome** [comment]
@yJunS   good idea
