### ISSUE TITLE
[推荐] - CI/CD with Jenkins and Ansible

### ISSUE THREAD

**Issue by yJunS** [jenkins-zh/jenkins-zh#222]
### 标题
CI/CD with Jenkins and Ansible

### 作者
[Balázs Németh](https://itnext.io/@balazsmaria)

### 来源
itnext

### 原文链接
https://itnext.io/ci-cd-with-jenkins-and-ansible-f41ef2b33977

### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

感谢 @0N0thing 推荐，我帮忙转发一下

**Comment by wwjgit** [comment]
认领文章翻译，申请加入。

**Comment by LinuxSuRen** [comment]
发送邀请了，欢迎加入
