### ISSUE TITLE
[推荐] - Using a k3s Kubernetes Cluster for Your GitLab Project

### ISSUE THREAD

**Issue by yJunS** [jenkins-zh/jenkins-zh#223]
### 标题
Using a k3s Kubernetes Cluster for Your GitLab Project

### 作者
[Luc Juggery](https://medium.com/@lucjuggery)

### 来源
Medium

### 原文链接
https://medium.com/better-programming/using-a-k3s-kubernetes-cluster-for-your-gitlab-project-b0b035c291a9

### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

**Comment by 0N0thing** [comment]
pick this
