### ISSUE TITLE
[推荐] - Validating JCasC configuration files using Visual Studio Code

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-zh/jenkins-zh#224]
### 标题
Validating JCasC configuration files using Visual Studio Code

### 作者
Sladyn Nunes

### 来源
Jenkins blog

### 原文链接
https://jenkins.io/blog/2020/02/25/vscode-caseStudy/

### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

**Comment by wenjunzhangp** [comment]
这个博客已经在很久之前翻译并且发不过了，具体见下文链接
[https://jenkins-zh.cn/wechat/articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code/](https://jenkins-zh.cn/wechat/articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code/)

**Comment by LinuxSuRen** [comment]
收到

**Comment by wenjunzhangp** [comment]
太速度了，哈哈
