### ISSUE TITLE
[推荐] - Using Nexus OSS as a proxy/cache for Docker images

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-zh/jenkins-zh#227]
### 标题
Using Nexus OSS as a proxy/cache for Docker images

### 作者
Maarten Tijhof

### 来源
https://wordpress.com/

### 原文链接
https://mtijhof.wordpress.com/2018/07/23/using-nexus-oss-as-a-proxy-cache-for-docker-images/

### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

**Comment by 0N0thing** [comment]
pick this
