### ISSUE TITLE
[推荐] - GitHub App authentication support released

### ISSUE THREAD

**Issue by donhui** [jenkins-zh/jenkins-zh#232]
### 标题 
GitHub App authentication support released

### 作者
Tim Jacomb

### 来源
https://jenkins.io/

### 原文链接
https://jenkins.io/blog/2020/04/16/github-app-authentication/#github-app-authentication-support-released

### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

**Comment by wenjunzhangp** [comment]
pick this~
抱歉，最近公司很忙，很久没未社区做过贡献啦，先接一个比较短的~~
预计完成时间周五6.12~~~

**Comment by LinuxSuRen** [comment]
非常欢迎，社区需要大家，也欢迎发动周围的朋友们一起加入！
