### ISSUE TITLE
[推荐] - How to Backup and Restore Jenkins. Complete Guide

### ISSUE THREAD

**Issue by donhui** [jenkins-zh/jenkins-zh#242]
### 标题
How to Backup and Restore Jenkins. Complete Guide

### 作者
oleksii_y

### 来源
medium.com

### 原文链接
https://medium.com/@_oleksii_/how-to-backup-and-restore-jenkins-complete-guide-62fc2f99b457

### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

**Comment by walker0921** [comment]
please assign it to me.
thanks

**Comment by donhui** [comment]
@walker0921 你应该也可以分配给自己的

**Comment by LinuxSuRen** [comment]
这个还没有合并呢，我先打开了
