### ISSUE TITLE
[推荐] - Create a CI/CD Pipeline with Kubernetes and Jenkins

### ISSUE THREAD

**Issue by yJunS** [jenkins-zh/jenkins-zh#251]
### 标题
Create a CI/CD Pipeline with Kubernetes and Jenkins

### 作者
Mohamed Ahmed

### 来源
gitconnected

### 原文链接
https://levelup.gitconnected.com/create-a-ci-cd-pipeline-with-kubernetes-and-jenkins-e16ae96bc51e

### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

**Comment by 0N0thing** [comment]
这篇翻译过了 [使用 Kubernetes 和 Jenkins 创建一个 CI/CD 流水线](https://mp.weixin.qq.com/s/QFrzFmn59nPXzxmaJ_mLQQ)

**Comment by LinuxSuRen** [comment]
@0N0thing 感谢指出来
