### ISSUE TITLE
[推荐] - Call for User Stories - Jenkins is the Way

### ISSUE THREAD

**Issue by donhui** [jenkins-zh/jenkins-zh#256]
### 标题
Call for User Stories - Jenkins is the Way

### 作者
Alyssa Tong, Mark Waite

### 来源
https://www.jenkins.io/node/

### 原文链接
https://www.jenkins.io/blog/2020/04/30/jenkins-is-the-way/

### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

**Comment by reneeteng** [comment]
举手。5月15之前可以完成翻译。

**Comment by donhui** [comment]
@reneeteng 分配给你了，感谢～～
