### ISSUE TITLE
[推荐] - Your DevOps Brain: Ways of Thinking, Ways of Working

### ISSUE THREAD

**Issue by 0N0thing** [jenkins-zh/jenkins-zh#266]
### 标题
Your DevOps Brain: Ways of Thinking, Ways of Working
### 作者
Helen Beal
### 来源
medium.com
### 原文链接
https://medium.com/itrevolution/your-devops-brain-ways-of-thinking-ways-of-working-a2b046708d3a
### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

**Comment by reneeteng** [comment]
领取啦，5月31日前完成任务。
