### ISSUE TITLE
[推荐] - Monitoring Linux Logs with Kibana and Rsyslog

### ISSUE THREAD

**Issue by 0N0thing** [jenkins-zh/jenkins-zh#274]
### 标题
Monitoring Linux Logs with Kibana and Rsyslog
### 作者
Antoine Solnichkin
### 来源
Medium
### 原文链接
https://medium.com/schkn/monitoring-linux-logs-with-kibana-and-rsyslog-4dfbbd287807
### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

**Comment by 0N0thing** [comment]
pick this

**Comment by LinuxSuRen** [comment]
可以试着和作者联系下，如果能获得授权就更好了。

**Comment by 0N0thing** [comment]
> 可以试着和作者联系下，如果能获得授权就更好了。

这篇文章下我给作者留言了，看看他的想法吧。

**Comment by LinuxSuRen** [comment]
好的
