### ISSUE TITLE
[推荐] - Machine Learning Plugin project - community bonding blog post 

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-zh/jenkins-zh#292]
### 标题
Machine Learning Plugin project - community bonding blog post 

### 作者
Loghi Perinpanayagam

### 来源
Jenkins Community

### 原文链接
https://www.jenkins.io/blog/2020/06/03/machine-learning-plugin-community-bonding/

### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

**Comment by wenjunzhangp** [comment]
pick this~~
预计完成时间6.22周一~
