### ISSUE TITLE
[推荐] - CI/CD With Argo On Kubernetes

### ISSUE THREAD

**Issue by 0N0thing** [jenkins-zh/jenkins-zh#299]
### 标题
CI/CD With Argo On Kubernetes
### 作者
Bouwe Ceunen
### 来源
medium.com
### 原文链接
https://medium.com/axons/ci-cd-with-argo-on-kubernetes-28c1a99616a9
### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

**Comment by 0N0thing** [comment]
pick this
但是我这个月的免费看的文章数已经超了，所以下个月才能看到全文，先提前pick了

**Comment by LinuxSuRen** [comment]
[CI_CD With Argo On Kubernetes - Axons - Medium.pdf](https://github.com/jenkins-zh/jenkins-zh/files/4818165/CI_CD.With.Argo.On.Kubernetes.-.Axons.-.Medium.pdf)
我提交个PDF上来，哈哈

**Comment by 0N0thing** [comment]
> [CI_CD With Argo On Kubernetes - Axons - Medium.pdf](https://github.com/jenkins-zh/jenkins-zh/files/4818165/CI_CD.With.Argo.On.Kubernetes.-.Axons.-.Medium.pdf)
> 我提交个PDF上来，哈哈

Excellent!那我可以愉快的看全文了！LOL
