### ISSUE TITLE
[Suggestion] - Jenkins Infrastructure: Stats, Updates, and AWS sponsorship 

### ISSUE THREAD

**Issue by donhui** [jenkins-zh/jenkins-zh#301]
This article will be published to Jenkins official WeChat.

### Title
Jenkins Infrastructure: Stats, Updates, and AWS sponsorship 

### Author
Olivier Vernin

### Source
https://www.jenkins.io/blog/

### Original Link
https://www.jenkins.io/blog/2020/06/17/infra-and-aws-donation/

### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

**Comment by wenjunzhangp** [comment]
pick this，预计完成日期 6.30周二~
