### ISSUE TITLE
[Suggestion] - Jenkins的kubernetes-plugin使用方法

### ISSUE THREAD

**Issue by sunweisheng** [jenkins-zh/jenkins-zh#309]
This article will be published to Jenkins official WeChat.

### Title
Jenkins的kubernetes-plugin使用方法

### Author
孙维晟

### Source
www.bluersw.com

### Original Link
https://github.com/sunweisheng/Jenkins/blob/master/Jenkins-Kubernetes.md

### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

**Comment by sunweisheng** [comment]
怎么加入中文社区的 GitHub 组织？

**Comment by LinuxSuRen** [comment]
@sunweisheng 感谢推荐文章，我来邀请您

**Comment by sunweisheng** [comment]
> @sunweisheng 感谢推荐文章，我来邀请您
> 这篇是您的原创文章，也可以直接提交到这个仓库。

明天了，谢谢您。

**Comment by LinuxSuRen** [comment]
如果是要投稿的话，直接提交PR即可。当前的issues，我关闭了。
