### ISSUE TITLE
[Suggestion] - 分享一个使用和学习Jenkins的文章列表

### ISSUE THREAD

**Issue by sunweisheng** [jenkins-zh/jenkins-zh#310]
This article will be published to Jenkins official WeChat.

### Title
使用和学习Jenkins的文章列表

### Author
孙维晟

### Source
www.bluersw.com

### Original Link
https://github.com/sunweisheng/Jenkins

### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

**Comment by LinuxSuRen** [comment]
这个不算是英文（或者其他外文）的推荐，我把对应的标签取消了。另外，如果是要投稿的话，直接提交PR即可。当前的issues，我也关闭了。
