### ISSUE TITLE
[合作社区] 首届中国 DevOps 社区流水线大赛

### ISSUE THREAD

**Issue by martinliu** [jenkins-zh/jenkins-zh#328]
活动名称：首届中国 DevOps 社区流水线大赛
活动时间：从 8 月 18 日到 10 月 18 日
活动官网：https://pipeline.devopsmeetup.com
报名网址链接：https://wj.qq.com/s2/6852880/c181/ 
报名二维码：

![](https://static.oschina.net/uploads/space/2020/0820/101617_ajlv_4217431.png)

请转发微信文案：https://mp.weixin.qq.com/s/pXXl8w-LbUC2wAYIIT_9xQ

![Pipeline+Craft_公众号封面首图_2020-08-28-0](https://user-images.githubusercontent.com/582423/91515208-36bd8400-e91b-11ea-8f74-2771306ac811.png)

海报：
![15471598487210_ pic_hd](https://user-images.githubusercontent.com/582423/91513287-92d1d980-e916-11ea-8430-a38503f95676.jpg)

活动类型：免费活动，中国DevOps社区流水线大赛采取线上赛形式举办活动，通过项目代码进行角逐切磋，打造浓郁的技术氛围。

后续活动：社区将在DevOps社区年会现场对获奖者进行颁奖表彰，并邀请部分获奖者参与社区年会的技术分享。

 
### 活动流程

01 报名参与

本活动旨在参与和学习流水线设计及实操，鼓励全国各地的DevOps实践者们针对流水线进行切磋。 比赛交付的应用程序可以是简单的Hello World应用，也可以是复杂的微服务架构项目。

02 打磨作品

以公开的代码仓库提交作品，GitLab、GitHub、Bitbucket和码云不限。自述文件中至少包含目标应用系统简介和流水线概述，便于评委和社区小伙伴了解你的项目。流水线项目是一个公开可见的状态，不限制CI 服务是 SaaS 或者自建。构建和交付的应用最好是可在线访问的。代码库里包含流水线关键配置的展示截图或者短视频（个人博客或者视频网站外链接）。

03 评分颁奖

比赛周期为 60 天，社区会对在最后提交日期前的有效作品进行评分。作品提交说明文档 、参加线上作品演示环节可获得附加分。

## 评奖和赞助

DevOps 社区评委打分，赞助商打分，社区投票。

奖品设置：社区和赞助商分别设置，一等奖 1 名，二等奖3 名，三等奖 5 名。

鸣谢赞助商： AWS、Elastic、GitLab、JFrog

## 协作推广

DevOps 社区已经将 Jenkins 中文社区的 log 在海报和活动官网上线。

请协助以下推广事宜：

- [x] 转发微信文案
- [x] 在各个社区微信群里转发活动宣传海报
- [x] 在其他相关社区推广渠道展示和推广本次活动
- [ ]  在 9 月的第二周提供一个线上主题分享，内容关于 Pipeline 的搭建流程和技巧，最好能和 GitLab、JFrog 和 k8 的技术相关。

**Comment by martinliu** [comment]
已经在其他活动网站上线了本次活动：


- https://huiyi.csdn.net/activity/product/goods_list?project_id=4627
- https://www.oschina.net/event/2318275
- https://www.hudongba.com/party/4rl9a.html

**Comment by LinuxSuRen** [comment]
公众号推文已经发出，[请查看](https://mp.weixin.qq.com/s?__biz=Mzg2MzAwNzU3Nw==&mid=2247486411&idx=2&sn=f3092071985187ae47a9cc4a74cd7bb0&chksm=ce7e6dfdf909e4eb0e5836d8c07f3f70afe00e4e528d274e32c64eb773ee15ba4f9e4648b5b9&token=662204332&lang=zh_CN#rd).

**Comment by LinuxSuRen** [comment]
![image](https://user-images.githubusercontent.com/1450685/92422340-8f104380-f1af-11ea-8ac9-a16ad9df2308.png)
上面是在社区微信群中的转发截图

**Comment by LinuxSuRen** [comment]
社区论坛上的推广链接 https://community.jenkins-zh.cn/t/devops/607

**Comment by martinliu** [comment]
Thank you.

**Comment by LinuxSuRen** [comment]
kind/outreach
