### ISSUE TITLE
[合作社区] KubeSphere 3.0.0 正式发布，社区官宣文章转载（8月31日）

### ISSUE THREAD

**Issue by FeynmanZhou** [jenkins-zh/jenkins-zh#329]
RT，下周一（8月31日）我们将通过 KubeSphere 社区公众号和官网等渠道官宣 3.0.0 GA，希望 Jenkins 中文社区能够在当天帮忙同步转发该文章。谢谢！

**Comment by LinuxSuRen** [comment]
好的，届时把推文地址贴在这里哈。

**Comment by LinuxSuRen** [comment]
感谢 @walker0921 帮忙[转发的推文](https://mp.weixin.qq.com/s/daiO8ldMjLu_KEzRacdIlw)

**Comment by FeynmanZhou** [comment]
非常感谢！ @LinuxSuRen @walker0921
