### ISSUE TITLE
[推荐] - Setup The Simplest CI With Bitbucket Pipelines

### ISSUE THREAD

**Issue by 0N0thing** [jenkins-zh/jenkins-zh#342]
### 标题
Setup The Simplest CI With Bitbucket Pipelines

### 作者
Ferenc Almasi

### 来源
medium.com

### 原文链接
https://medium.com/swlh/setup-the-simplest-ci-with-bitbucket-pipelines-7989e934e700
### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

**Comment by 0N0thing** [comment]
pick this

**Comment by wwjgit** [comment]
认领翻译，预计10月9日完成
