### ISSUE TITLE
jenkins的多分支pipeline如何在配置里编写Jenkinsfile

### ISSUE THREAD

**Issue by dengliyao** [jenkins-zh/jenkins-zh#354]
现在多分支流水线只能在项目里加上Jenkinsfile文件，怎样在配置里编写Jenkinsfile，是否需要安装插件

**Comment by LinuxSuRen** [comment]
您好，我这边有思路，如果不是非常着急的话，最近几天我可以把这个插件开发出来。

**Comment by dengliyao** [comment]
> 您好，我这边有想法，如果不是非常着急的话，最近几天我可以把这个插件开发出来。

你好，不急的，谢谢，等插件出来我再测试

**Comment by LinuxSuRen** [comment]
我已经提交了一个 PR，并且上传了一个临时可用的插件文件，你可以从下面的地址下载到 https://github.com/LinuxSuRen/pipeline-multibranch-defaults-plugin/releases/tag/draft-v0.1
