### ISSUE TITLE
[社区合作] 云原生 Meetup | KubeSphere & Friends 2020

### ISSUE THREAD

**Issue by FeynmanZhou** [jenkins-zh/jenkins-zh#396]
Meetup 相关信息如下，希望 Jenkins 中文社区帮忙转发🤝 谢谢！

活动信息：https://mp.weixin.qq.com/s/r0O-WOpJfsRrDD7Ln_hc8w
时间：12 月 19 日下午 13:00 - 18:00
地点：aiospace 机遇空间
地址：北京市朝阳区798艺术区D区798西街
报名方式：参考以上文章

**Comment by LinuxSuRen** [comment]
收到，安排今晚推送

**Comment by LinuxSuRen** [comment]
提前发出来了 https://mp.weixin.qq.com/s/O885fuGVO1XUR1XfbPmytQ
