### ISSUE TITLE
[教程大纲]基于Jenkins的阿里云ECS使用介绍

### ISSUE THREAD

**Issue by zhongwandong** [jenkins-zh/jenkins-zh#408]
#### 视频教程里面的脚本文件如下：

                  pipeline {
                      agent { label 'alibabacloud' }
    	                  tools {
                                        maven 'apache-maven-3.6.3' 
                                        jdk 'jdk1.8'
                                  }
                          stages {
                              stage('Environment configure') {
        	                      
                                  steps {
                                      sh 'echo "environment configure begin"'
                                      sh 'yum install -y git'
              	                     sh 'echo "environment configure end"'
                                  }
                              }
                              stage('compile code with alibabacloud ecs plugin'){
          	                      steps{
          	                          sh 'rm -rf *'
          	                          sh 'git clone https://github.com/devops-ws/learn-pipeline-java.git'
		                          sh 'cd ./learn-pipeline-java && mvn clean package && ls target/'
		                          sh 'echo "End of process"'
          	                      }
                              }
                              stage('Archive') {
                                      steps {
                                          archiveArtifacts artifacts: 'learn-pipeline-java/target/*.jar', fingerprint: true 
                                      }
                              }
                      }

**Comment by zhongwandong** [comment]
大家看下有什么不妥可以提出来，欢迎吐槽

**Comment by LinuxSuRen** [comment]
该教程已经完成，先关闭了。
/close
