### ISSUE TITLE
[转载] - 使用 Jenkins、Docker 构建部署 Serverless 应用

### ISSUE THREAD

**Issue by donhui** [jenkins-zh/jenkins-zh#418]
### 标题
使用 Jenkins、Docker 构建部署 Serverless 应用

### 作者
donghui

### 来源
ServerlessLife 公众号（已设置转载白名单）

### 原文链接
https://mp.weixin.qq.com/s/Oo9EYlIVZmaWcDV1yo3B1Q

**Comment by LinuxSuRen** [comment]
我感觉可以转发，是和社区主题相关的，周二作为二条转发，是否可以。

**Comment by donhui** [comment]
可以的～

**Comment by LinuxSuRen** [comment]
已转发 https://mp.weixin.qq.com/s/uhA1IObiMLaZut3teirxuQ，期待更多好文章。
