### ISSUE TITLE
[推荐] - Jenkins Operator becomes an official sub-project! 

### ISSUE THREAD

**Issue by donhui** [jenkins-zh/jenkins-zh#445]
### 标题
Jenkins Operator becomes an official sub-project! 

### 作者
Bartek Antoniak, Sylwia Brant

### 来源
https://www.jenkins.io/

### 原文链接
https://www.jenkins.io/blog/2021/04/15/jenkins-operator-sub-project/

### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

/kind translation

**Comment by lxbzmy** [comment]
`/assign`
计划 2021年04月30日完成
