### ISSUE TITLE
[分享] 以Alibaba Dragonwell为例介绍AdoptOpenJdk构建测试流程

### ISSUE THREAD

**Issue by joeyleeeeeee97** [jenkins-zh/jenkins-zh#460]
## 背景
- Dragonwell简介
-- OracleJDK--OpenJDK产品策略
-- Dragonwell基于Adoptium提供的高质量构建
## 方案
- Dragonwell产品流程图(与AJDK, OpenJDK关系; 最近发布的alpine和即将发布的riscv)
- AdoptOpenJdk发布测试周期, 运维以及获取渠道
- 对于特性持续性能测试, 追踪收益
-- 王婆卖瓜? 透明测试, 帮助客户自主验证
## 展望
- 丰富领域相关测试集
- 沉淀性能分析工具和平台

**Comment by LinuxSuRen** [comment]
我们周日晚八点会在[哔哩哔哩](https://space.bilibili.com/433584098)上直播该分享
