### ISSUE TITLE
[Suggestion] - 

### ISSUE THREAD

**Issue by ysq5202121** [jenkins-zh/jenkins-zh#463]
This article will be published to Jenkins official WeChat.

### 认领
需要认领的同学，请确认是否加入了[中文社区的 GitHub 组织](https://github.com/orgs/jenkins-zh/people)。如果没有的话，请在下面留言，管理员会邀请你进入。
如果已经是当前组织的成员的话，可以直接把当前任务分配给自己，并留言说明预计完成时间。

**Comment by LinuxSuRen** [comment]
不知道您打开这个issue的希望做什么，看起来是没有内容的，先关闭了，如有需要可以再次打开
