### ISSUE TITLE
Jenkins 中文社区活动排序

### ISSUE THREAD

**Issue by shenxianpeng** [jenkins-zh/jenkins-zh#93]
打开Jenkins 中文社区官网： https://jenkins-zh.cn/event/ 活动没有按照一定的规则排序
如果能够按照时间或是城市进行排序，个人觉得可以方便查看过去，什么时间，在哪里举办过什么活动；未来什么时间，在哪里还有什么活动可以参加会变得更加清晰。

倾向于将 主题/日期 拆开来，将未开始的活动放在上方，已结束的活动按时间排序放在下方。如下：

| 日期 | 主题 | 城市 | 位置 | 状态 | 赞助 |
|---|---|---|---|---|---|
| 2019-10-25 | 持续交付黑客松 | 北京 | 海淀区知春路56号中航科技大厦 | 计划中 | 立即申请 |
| 2019-09-07 | 主题 | 上海 | 待定 | 计划中 | 立即申请 |
| 2019-08-24 | 开源人线下见面会 | 北京 | 北京市朝阳区东直门外斜街56号A座302 | 报名中 | 赞助商|
| 2019-07-27 | 持续交付工作坊 | 北京 | 海淀区知春路56号中航科技大厦 | 已结束 | 赞助商 |
| 2019-06-22 | Jenkins 流水线工作坊 | 北京 | 海淀区知春路56号中航科技大厦 | 已结束 | 赞助商 |
| 2019-04-25 | 2019 Cloud Native Community Day | 北京 | 海淀区知春路56号中航科技大厦 | 已结束 | 赞助商 |

**Comment by LinuxSuRen** [comment]
确实是，不过，在排序函数的使用上遇到些问题没有解决，您可以帮忙一起看一下。

**Comment by shenxianpeng** [comment]
想尝试但windows环境还没配好

**Comment by LinuxSuRen** [comment]
嗯，这些对Windows的支持不太友好。可以在 Linux 虚拟机上试试

**Comment by yJunS** [comment]
> 想尝试但windows环境还没配好

windows可以安装chocolate，然后`choco install hugo`，其他基本上就可以

**Comment by shenxianpeng** [comment]
谢谢环境好了。

**Comment by shenxianpeng** [comment]
提了 PR 在这里 https://github.com/jenkins-zh/jenkins-zh/pull/96，请查看，提意见。

**Comment by yJunS** [comment]
好的。已查看

**Comment by shenxianpeng** [comment]
Closing as fixed
